/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class SilverbirdAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    SilverbirdAudioProcessorEditor (SilverbirdAudioProcessor&);
    ~SilverbirdAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    SilverbirdAudioProcessor& processor;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (SilverbirdAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
