/*
 ==============================================================================
 
 This file was auto-generated by the Introjucer!
 
 It contains the basic startup code for a Juce application.
 
 ==============================================================================
*/

#include "../Plugin/JuceLibraryCode/AppConfig.h"
 
#include "JuceHeader.h"
#include "StandaloneFilterWindow.h"



class SilverbirdAppApplication  : public JUCEApplication
{
public:
    SilverbirdAppApplication() {}
    
    void initialise (const String& commandLine)
    {
        //ApplicationProperties::setStorageParameters (T("SilverbirdApp"), String::empty, T("SilverbirdApp"), 400, PropertiesFile::storeAsXML);
        
        pluginWindow = new StandaloneFilterWindow (ProjectInfo::projectName, Colours::black, NULL, false);
        
        pluginWindow->setTitleBarButtonsRequired (DocumentWindow::allButtons, false);
        pluginWindow->setVisible (true);
        //pluginWindow->setUsingNativeTitleBar(true); // comment out to get to the application (options) button ;)
        
        pluginWindow->setResizable (false, false);
        pluginWindow->centreWithSize(pluginWindow->getWidth(), pluginWindow->getHeight());
    }
    
    void shutdown()
    {
        pluginWindow = nullptr; // (deletes our window)
    }
    
    void systemRequestedQuit()
    {
        quit();
    }
    
    void anotherInstanceStarted (const String& commandLine)
    {
        // When another instance of the app is launched while this one is running,
        // this method is invoked, and the commandLine parameter tells you what
        // the other instance's command-line arguments were.
    }

    const String getApplicationName()       {
        return ProjectInfo::projectName;
    }
    
    const String getApplicationVersion()    {
        return ProjectInfo::versionString;
    }
    
    bool moreThanOneInstanceAllowed() {
        return true;
    }
 
private:
    ScopedPointer<StandaloneFilterWindow> pluginWindow;
};


//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (SilverbirdAppApplication)
